//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lunz.Data.EDT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Basic_DataDictionary
    {
        public Basic_DataDictionary()
        {
            this.Basic_Announcement = new HashSet<Basic_Announcement>();
            this.Basic_BankInfo = new HashSet<Basic_BankInfo>();
            this.Basic_CompanyInfo = new HashSet<Basic_CompanyInfo>();
            this.Basic_DataDictionary1 = new HashSet<Basic_DataDictionary>();
        }
    
        public System.Guid Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<System.Guid> ParentId { get; set; }
        public string StringValue { get; set; }
        public Nullable<int> IntValue { get; set; }
        public Nullable<double> FloatValue { get; set; }
        public Nullable<bool> BoolValue { get; set; }
        public Nullable<System.DateTime> DateTimeValue { get; set; }
        public string Description { get; set; }
        public int SortOrder { get; set; }
        public Nullable<System.Guid> CreatedById { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.Guid> UpdatedById { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public bool Deleted { get; set; }
        public Nullable<System.Guid> DeletedById { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
    
        public virtual ICollection<Basic_Announcement> Basic_Announcement { get; set; }
        public virtual ICollection<Basic_BankInfo> Basic_BankInfo { get; set; }
        public virtual ICollection<Basic_CompanyInfo> Basic_CompanyInfo { get; set; }
        public virtual ICollection<Basic_DataDictionary> Basic_DataDictionary1 { get; set; }
        public virtual Basic_DataDictionary Basic_DataDictionary2 { get; set; }
    }
}
