//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lunz.Data.EDT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Basic_CompanyInfo
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string NameEN { get; set; }
        public string Abbreviation { get; set; }
        public Nullable<int> Number { get; set; }
        public System.Guid TypeCode { get; set; }
        public string TypeName { get; set; }
        public string BusinessLicense { get; set; }
        public Nullable<System.DateTime> BusinessTerm { get; set; }
        public string TaxRegistrationNo { get; set; }
        public Nullable<System.DateTime> Founded { get; set; }
        public Nullable<decimal> RegistrationCapital { get; set; }
        public string BusinessScope { get; set; }
        public string Telephone { get; set; }
        public string Address { get; set; }
        public string Fax { get; set; }
        public string PostalCode { get; set; }
        public string OrganizationCode { get; set; }
        public string RegisteredAddress { get; set; }
        public string CompanyEmail { get; set; }
        public string Remarks { get; set; }
        public string LegalName { get; set; }
        public string LegalIDCard { get; set; }
        public string LegalTel { get; set; }
        public string LegalPostalCode { get; set; }
        public string LegalAddress { get; set; }
        public string LegalPhone { get; set; }
        public string LegaiEmail { get; set; }
        public string ContactName { get; set; }
        public string ContactIDCard { get; set; }
        public string ContactTel { get; set; }
        public string ContactPostalCode { get; set; }
        public string ContactAddress { get; set; }
        public string ContactPhone { get; set; }
        public string ContactEmail { get; set; }
        public int SortOrder { get; set; }
        public Nullable<System.Guid> CreatedById { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.Guid> UpdatedById { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public bool Deleted { get; set; }
        public Nullable<System.Guid> DeletedById { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
    
        public virtual Membership_User Membership_User { get; set; }
        public virtual Basic_DataDictionary Basic_DataDictionary { get; set; }
    }
}
