//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lunz.Data.EDT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Basic_Logs
    {
        public System.Guid Id { get; set; }
        public string LogLevel { get; set; }
        public string Message { get; set; }
        public System.DateTime LogTime { get; set; }
    }
}
