//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lunz.Data.EDT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Membership_User
    {
        public Membership_User()
        {
            this.Membership_AuthToken = new HashSet<Membership_AuthToken>();
            this.Membership_UserResetPassword = new HashSet<Membership_UserResetPassword>();
            this.Basic_CompanyInfo = new HashSet<Basic_CompanyInfo>();
        }
    
        public System.Guid Id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string DisplayName { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public int MemberType { get; set; }
        public Nullable<System.Guid> VIPLevelId { get; set; }
        public bool Actived { get; set; }
        public bool Approved { get; set; }
        public Nullable<System.DateTime> LatestLoginAt { get; set; }
        public Nullable<System.Guid> CreatedById { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.Guid> UpdatedById { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public bool Deleted { get; set; }
        public Nullable<System.Guid> DeletedById { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
    
        public virtual ICollection<Membership_AuthToken> Membership_AuthToken { get; set; }
        public virtual Membership_VIPLevel Membership_VIPLevel { get; set; }
        public virtual ICollection<Membership_UserResetPassword> Membership_UserResetPassword { get; set; }
        public virtual ICollection<Basic_CompanyInfo> Basic_CompanyInfo { get; set; }
    }
}
