//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lunz.Data.EDT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Object_AttributeCategory
    {
        public Object_AttributeCategory()
        {
            this.Object_AttributeFiled = new HashSet<Object_AttributeFiled>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid AreaId { get; set; }
        public string Name { get; set; }
        public int SortOrder { get; set; }
        public Nullable<System.Guid> CreatedById { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.Guid> UpdatedById { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public bool Deleted { get; set; }
        public Nullable<System.Guid> DeletedById { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
    
        public virtual Object_AttributeArea Object_AttributeArea { get; set; }
        public virtual ICollection<Object_AttributeFiled> Object_AttributeFiled { get; set; }
    }
}
