//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lunz.Data.EDT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_ProductDefinition
    {
        public Product_ProductDefinition()
        {
            this.Product_ProductGpsFee = new HashSet<Product_ProductGpsFee>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string ProductTypeCode { get; set; }
        public string VehicleTypeCode { get; set; }
        public Nullable<double> DownPayment { get; set; }
        public Nullable<double> DownPaymentStart { get; set; }
        public Nullable<double> DownPaymentEnd { get; set; }
        public bool DownPaymentEditable { get; set; }
        public string DownPaymentSumTypeCode { get; set; }
        public Nullable<double> Margin { get; set; }
        public Nullable<double> MarginStart { get; set; }
        public Nullable<double> MarginEnd { get; set; }
        public bool MarginEditable { get; set; }
        public string MarginSumTypeCode { get; set; }
        public Nullable<double> Fee { get; set; }
        public Nullable<double> FeeStart { get; set; }
        public Nullable<double> FeeEnd { get; set; }
        public bool FeeEditable { get; set; }
        public string FeeSumTypeCode { get; set; }
        public string FeeCalTypeCode { get; set; }
        public Nullable<double> FinalPayment { get; set; }
        public Nullable<double> FinalPaymentStart { get; set; }
        public Nullable<double> FinalPaymentEnd { get; set; }
        public bool FinalPaymentEditable { get; set; }
        public string FinalPaymentSumTypeCode { get; set; }
        public Nullable<double> InterestRate { get; set; }
        public Nullable<double> InterestRateStart { get; set; }
        public Nullable<double> InterestRateEnd { get; set; }
        public bool InterestRateEditable { get; set; }
        public Nullable<int> Lease { get; set; }
        public Nullable<int> LeaseStart { get; set; }
        public Nullable<int> LeaseEnd { get; set; }
        public bool LeaseEditable { get; set; }
        public string LendingTypeCode { get; set; }
        public string MarginDealTypeCode { get; set; }
        public string GpsInstallTypeCode { get; set; }
        public string PurchaseTaxSumTypeCode { get; set; }
        public string InsuranceSumTypeCode { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public Nullable<decimal> FinancingVolumeStart { get; set; }
        public Nullable<decimal> FinancingVolumeEnd { get; set; }
        public string FinancingVolumeSumTypeCode { get; set; }
        public string CalTypeId { get; set; }
        public bool GpsFeeEditable { get; set; }
        public int SortOrder { get; set; }
        public Nullable<System.Guid> CreatedById { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.Guid> UpdatedById { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public bool Deleted { get; set; }
        public Nullable<System.Guid> DeletedById { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
    
        public virtual ICollection<Product_ProductGpsFee> Product_ProductGpsFee { get; set; }
    }
}
